name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: SPOJ_PT07Z
      run: g++ SPOJ_PT07Z.cpp
    - name: produce output
      run: ./a.out < ./test_cases/SPOJ_PT07Z_1_in.txt > ./SPOJ_PT07Z_1_run.txt
    - name: show output
      run: echo "produced:" && cat ./SPOJ_PT07Z_1_run.txt && echo "expected:" && cat ./test_cases/SPOJ_PT07Z_1_out.txt
    - name: difference
      run: diff ./SPOJ_PT07Z_1_run.txt ./test_cases/SPOJ_PT07Z_1_out.txt
#     - name: configure
#       run: ./configure
#     - name: make
#       run: make
#     - name: make check
#       run: make check
#     - name: make distcheck
#       run: make distcheck

