name: SPOJ_PT07Z
# acknowledgement: https://github.com/firepress-org/rclone-in-docker/blob/master/.github/workflows/ci_dockerfile_is_master.yml

on:
  push:
    branches: [ master ]
    paths:
      - 'test_cases/SPOJ_PT07Z*'
      - '.github/workflows/SPOJ_PT07Z*'
      - 'SPOJ_PT07Z*' 
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: setup env
      run: |
        echo SPOJ_PT07Z > NAME
        echo 1 > NUM
    - name: SPOJ_PT07Z
      run: g++ ./$(cat NAME).cpp
    - name: produce output
      run: |
        cases=0
        for file in ./test_cases/$(cat NAME)_*_in.txt; do
          cases=$((cases+1))
          ./a.out < $file > ./$(cat NAME)_${cases}_run.txt
        done
        
    - name: show output
      run: |
        cases=0
        for file in ./test_cases/$(cat NAME)_*_in.txt; do
          cases=$((cases+1))
          echo "Case ${cases}:"
          echo "==========input========:" && cat $file
          echo ""
          echo "========produced=======:" && cat ./$(cat NAME)_${cases}_run.txt
          echo ""
          echo "========expected=======:" && cat ./test_cases/$(cat NAME)_${cases}_out.txt
          echo ""
          echo "======================="
        done
    - name: difference
      run: |
        cases=0
        for file in test_cases/$(cat NAME)_*_in.txt; do
          cases=$((cases+1))
          diff ./$(cat NAME)_${cases}_run.txt ./test_cases/$(cat NAME)_${cases}_out.txt
        done
#     - name: configure
#       run: ./configure
#     - name: make
#       run: make
#     - name: make check
#       run: make check
#     - name: make distcheck
#       run: make distcheck
