name: SPOJ_PT07Z

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: configure environment
      run: export NAME=SPOJ_PT07Z && export NUM=1
      
    - name: SPOJ_PT07Z
      run: g++ "$NAME".cpp
    - name: produce output
      run: ./a.out < ./test_cases/"$NAME"_"$NUM"_in.txt > ./"$NAME"_"$NUM"_run.txt
    - name: show output
      run: echo "input:" && cat ./test_cases/"$NAME"_"$NUM"_in.txt && echo "produced:" && cat ./"$NAME"_"$NUM"_run.txt && echo "expected:" && cat ./test_cases/"$NAME"_"$NUM"_out.txt
    - name: difference
      run: diff ./"$NAME"_"$NUM"_run.txt ./test_cases/"$NAME"_"$NUM"_out.txt
#     - name: configure
#       run: ./configure
#     - name: make
#       run: make
#     - name: make check
#       run: make check
#     - name: make distcheck
#       run: make distcheck
