name: uva_11838
# acknowledgement: https://github.com/firepress-org/rclone-in-docker/blob/master/.github/workflows/ci_dockerfile_is_master.yml

on:
  push:
    branches: [ master ]
    paths:
      - 'test_cases/uva_11838*'
      - '.github/workflows/uva_11838*'
      - 'uva_11838*' 
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: setup env
      run: |
        echo uva_11838 > NAME
        echo 1 > NUM
    - name: uva_11838
      run: g++ ./$(cat NAME).cpp
    - name: produce output
      run: |
        cases=0
        for file in test_cases/$(cat NAME)_*_in.txt; do
          cases=$((cases+1))
          ./a.out < file > ./$(cat NAME)_${cases}_run.txt
        done
        
    - name: show output
      run: |
        cases=0
        for file in test_cases/$(cat NAME)_*_in.txt; do
          cases=$((cases+1))
          echo "Case ${cases}:"
          echo "==========input========:" && cat file
          echo ""
          echo "========produced=======:" && cat ./$(cat NAME)_${cases}_run.txt
          echo ""
          echo "========expected=======:" && cat ./test_cases/$(cat NAME)_${cases}_out.txt
          echo ""
          echo "======================="
        done
    - name: difference
      run: |
        cases=0
        for file in test_cases/$(cat NAME)_*_in.txt; do
          cases=$((cases+1))
          diff ./$(cat NAME)_${cases}_run.txt ./test_cases/$(cat NAME)_${cases}_out.txt
        done

